timezone: "Asia/Karachi"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-purgecss

# Required for jekyly-purgecss. Defaults to ./css
css_dir: "assets/css"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - vendor
  - node_modules
